accounts/urls.py
from django.conf.urls import  url
from django.contrib import admin
from django.urls import path,re_path,include

from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    # path('login', views.Login.as_view(), name='login'),
    url(r'^login/$', views.LoginView.as_view(extra_context={'next':'next'}), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),

]

carts/urls.py
from django.conf.urls import  url
from .views import cart
from products.views import update_cart,checkout_home

app_name = 'cart'

urlpatterns = [
 url(r'^$',cart,name='cart'),
 url(r'^updatecart/$',update_cart,name='updatecart'),
 url(r'^checkout/$',checkout_home,name='checkout'),


]

django_ecom/urls.py
from django.conf.urls import  url
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static
from products.views import ProductListView,\
    ProductDetailView,ProductFeaturedListView,ProductFeaturedDetailView
from carts.views import cart


urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^accounts/', include("accounts.urls", namespace='accounts')),
    url(r'^cart/', include("carts.urls", namespace='carts')),
    url(r'^$',ProductListView.as_view(), name='productlist'),
    path('featured', ProductFeaturedListView.as_view(), name='featured_list'),
    path('products/<slug:slug>', ProductDetailView.as_view(), name='productdetail'),
    url(r'^featured/(?P<slug>\d+)/$',ProductFeaturedDetailView.as_view())

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save,m2m_changed
User = settings.AUTH_USER_MODEL

class CartManager(models.Manager): # handle the business logic of cart
    def get_cart_or_create(self,request): # get existing cart-means stored in cache by user in past or create a new one
        # define a variable cart_id which will check the session if there is any item exist in the cart or not
        cart_id = request.session.get('cart_id', None)  # if there is cart get the cart id or if not any cart exist set it to NOne
        qs = self.get_queryset().filter(id=cart_id) # just filter the cart_id with get_queryset, qs will check the data searchng by and id , if there is any card_id available
        if qs.count() == 1:  # select the number of rows matching the query and check there is one
            new_obj = False # we set it False initially  because the object is not new,and its the existed one which is a previous cart,
            print('card id exist- cause its stored in session')
            cart_obj = qs.first()  # if there is one item we retrieve it by first() and store it by variable cart_obj
            if request.user.is_authenticated and cart_obj.user is None: # if user is an authenticated user and not saved earliar with corrosponding cart id that means the cart_user_id table row is empty
                cart_obj.user = request.user # referring  the current logged in users as the user of the cart
                cart_obj.save() # save the cart
        else: # if there is not any existing cart in the session
            print("New cart created")
            # now create a object cart_obj of the Cart model which will instantiate the Cart- will need user as as argument
            cart_obj = Cart.objects.create_cart(user=request.user)  # creating another cart because it doesn't exist
            new_obj = True # because its new cart
            request.session['cart_id'] = cart_obj.id # the corresponding cart id will be passed in the session and stored in the variable cart_id
        return cart_obj,new_obj # passing the two object either new cart or existing cart


    def create_cart(self,user=None):
        user_obj = None # primarily empty or initialize the user_obj as NOne  - there is no user
        if user is not None:
            if user.is_authenticated: # check if user is valid user
                user_obj = user_obj # change the user None to existed one- because there is one authenticate user
        # To create and save an object in a single step, use the create() method.
        return self.model.objects.create(user=user_obj) # instantiate the user attribute of the Cart model class with the create method and the variable user_obj

class Cart(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True) # any user both logged in and anonymous can add to cart
    products = models.ManyToManyField(Product,blank=True) # cart can be empty
    subtotal = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    # Django adds a Manager with the name "objects" to every Django model class.
    objects = CartManager() # pass all the business logic of CartManager to the Cart Model class- similar to inheritance
    # NOw we can access all the method and attribute of CartManager class

    def __str__(self):
        return str(self.id)




def m2m_changed_cart_receiver(sender,instance,action,*args,**kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all() # here instance keyword refer to the Current Instance we are working with
        total = 0
        subtotal = 0
        for item in products:
            total+= item.price
        print(total)
        print(subtotal)
        instance.subtotal =  total
        instance.save()

m2m_changed.connect(m2m_changed_cart_receiver,sender=Cart.products.through)

def pre_save_cart_receiver(sender,instance,*args,**kwargs):
    if instance.subtotal > 0:
        instance.total = instance.subtotal +10  #*1.08
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver,sender=Cart)

carts/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from .models import Cart
from products.models import Product
from django.conf import settings


def cart(request): # session will get cart when the url is being requested
    cart_obj,new_obj = Cart.objects.get_cart_or_create(request) # create two instance with the same name as refer to the get_cart_or_create with the parent model class Cart -the method belong to Cart now
    products = cart_obj.products.all() #will returns the list of products. product is the many to many model field- here we did this for testing purpose
    total = 0
    for item in products:
        total += item.price # price is the attribute of Cart model
    cart_obj.total = total
    cart_obj.save()

    return render(request,'carts/cart_home.html',{'cart':cart_obj})

carts/templates/carts/cart_home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
	<!--================Home Banner Area =================-->
	<section class="banner_area">
		<div class="banner_inner d-flex align-items-center">
			<div class="container">
				<div class="banner_content text-center">
					<h2>Shopping Cart</h2>
					<div class="page_link">
						<a href="index.html">Home</a>
						<a href="carthome.html">Cart</a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================End Home Banner Area =================-->

		<!--================Cart Area =================-->
	<section class="cart_area">
		<div class="container">
			<div class="cart_inner">
				<div class="table-responsive">
                    {% if cart.products.exists %}
					    <table class="table">
						<thead>
							<tr>
								<th scope="col">Product</th>
								<th scope="col">Price</th>
								<th scope="col">Quantity</th>
								<th scope="col">Total</th>
							</tr>
						</thead>
                        {%for product in cart.products.all %}
						    <tbody>

							<tr>
								<td>
                                    <div class="container">
                                            <div class="col-md-2 px-0">
                                                <img src="{{product.image.url}}" class="img-fluid">
                                            </div>
                                            <div class="media-body">
                                                <p><a href="{{ product.get_absolute_url }}">{{product.title}}</a></p>
												{% include 'carts/updatecart.html' with product=product cart=cart in_cart=True %}
                                            </div>
                                    </div>

                                </td>
								<td>
									<h5>${{product.price}}</h5>
								</td>
								<td>
									<!--<div class="product_count">-->
										<!--<input type="text" name="qty" id="sst" maxlength="12" value="1" title="Quantity:" class="input-text qty">-->
										<!--<button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;"-->
										 <!--class="increase items-count" type="button">-->
											<!--<i class="lnr lnr-chevron-up"></i>-->
										<!--</button>-->
										<!--<button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value&#45;&#45;;return false;"-->
										 <!--class="reduced items-count" type="button">-->
											<!--<i class="lnr lnr-chevron-down"></i>-->
										<!--</button>-->
									<!--</div>-->
								</td>
								<td>
									<h5>${{product.price}}</h5>
								</td>
							</tr>
                            {% endfor %}
							<!--<tr class="bottom_button">-->
								<!--<td>-->
									<!--<a class="gray_btn" href="#">Update Cart</a>-->
								<!--</td>-->
								<!--<td>-->

								<!--</td>-->
								<!--<td>-->

								<!--</td>-->
								<!--<td>-->
									<!--<div class="cupon_text">-->
										<!--<input type="text" placeholder="Coupon Code">-->
										<!--<a class="main_btn" href="#">Apply</a>-->
										<!--<a class="gray_btn" href="#">Close Coupon</a>-->
									<!--</div>-->
								<!--</td>-->
							<!--</tr>-->
							<tr>
								<td>
									<h5>Subtotal</h5>
								</td>
								<td>
									<h5>{{cart.subtotal}}</h5>
								</td>
                                <td>
									<h5>Total</h5>
								</td>
								<td>
									<h5>{{cart.total}}</h5>
								</td>


							</tr>
							<tr>
								<td>
									<div class="checkout_btn_inner">
										<a class="gray_btn" href="#">Continue Shopping</a>
										<a class="main_btn" href="{% url 'carts:checkout'%}">Proceed to checkout</a>
									</div>
								</td>
							</tr>
							</tbody>
					</table>
                    {% else %}
                    <h4 style="text-align:center">Cart is empty</h4>
                    {% endif %}
				</div>
			</div>
		</div>
	</section>
	<!--================End Cart Area =================-->
{% endblock %}

carts/templates/carts/checkout.html
{% extends 'base.html' %}
{% block content %}
{% load static %}




<!--================Home Banner Area =================-->
	<section class="banner_area">
		<div class="banner_inner d-flex align-items-center">
			<div class="overlay"></div>
			<div class="container">
				<div class="banner_content text-center">
					<h2>Product Checkout</h2>
					<div class="page_link">
						<a href="index.html">Home</a>
						<a href="checkout.html">Checkout</a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================End Home Banner Area =================-->




<!--================Checkout Area =================-->
	<section class="checkout_area section_gap">
		<div class="container">

			{% if not billing_profile %}
			<div class="returning_customer">
				<div class="check_title">
					<h2>Returning Customer?
						<a href="#">Click here to login</a>
					</h2>
				</div>
				<p>If you have shopped with us before, please enter your details in the boxes below. If you are a new customer, please proceed
					to the Billing & Shipping section.</p>
			</div>
			{% include 'carts/snippetform.html' with form=login_form next=request.build_absolute_uri %}
			<div class="cupon_area">
				<div class="check_title">
					<h2>Have a coupon?
						<a href="#">Click here to enter your code</a>
					</h2>
				</div>
				<input type="text" placeholder="Enter coupon code">
				<a class="tp_btn" href="#">Apply Coupon</a>
			</div>
			{% else %}
			<div class="billing_details">
				<div class="row">
					<div class="col-lg-8">
						<h3>Billing Details</h3>
						<form class="row contact_form" action="#" method="post" novalidate="novalidate">
							<div class="col-md-6 form-group p_star">
								<input type="text" class="form-control" id="first" name="name">
								<span class="placeholder" data-placeholder="First name"></span>
							</div>
							<div class="col-md-6 form-group p_star">
								<input type="text" class="form-control" id="last" name="name">
								<span class="placeholder" data-placeholder="Last name"></span>
							</div>
							<div class="col-md-12 form-group">
								<input type="text" class="form-control" id="company" name="company" placeholder="Company name">
							</div>
							<div class="col-md-6 form-group p_star">
								<input type="text" class="form-control" id="number" name="number">
								<span class="placeholder" data-placeholder="Phone number"></span>
							</div>
							<div class="col-md-6 form-group p_star">
								<input type="text" class="form-control" id="email" name="compemailany">
								<span class="placeholder" data-placeholder="Email Address"></span>
							</div>
							<div class="col-md-12 form-group p_star">
								<select class="country_select">
									<option value="1">Country</option>
									<option value="2">Country</option>
									<option value="4">Country</option>
								</select>
							</div>
							<div class="col-md-12 form-group p_star">
								<input type="text" class="form-control" id="add1" name="add1">
								<span class="placeholder" data-placeholder="Address line 01"></span>
							</div>
							<div class="col-md-12 form-group p_star">
								<input type="text" class="form-control" id="add2" name="add2">
								<span class="placeholder" data-placeholder="Address line 02"></span>
							</div>
							<div class="col-md-12 form-group p_star">
								<input type="text" class="form-control" id="city" name="city">
								<span class="placeholder" data-placeholder="Town/City"></span>
							</div>
							<div class="col-md-12 form-group p_star">
								<select class="country_select">
									<option value="1">District</option>
									<option value="2">District</option>
									<option value="4">District</option>
								</select>
							</div>
							<div class="col-md-12 form-group">
								<input type="text" class="form-control" id="zip" name="zip" placeholder="Postcode/ZIP">
							</div>
							<div class="col-md-12 form-group">
								<div class="creat_account">
									<input type="checkbox" id="f-option2" name="selector">
									<label for="f-option2">Create an account?</label>
								</div>
							</div>
							<div class="col-md-12 form-group">
								<div class="creat_account">
									<h3>Shipping Details</h3>
									<input type="checkbox" id="f-option3" name="selector">
									<label for="f-option3">Ship to a different address?</label>
								</div>
								<textarea class="form-control" name="message" id="message" rows="1" placeholder="Order Notes"></textarea>
							</div>
						</form>
					</div>
					<div class="col-lg-4">
						<div class="order_box">
							<h2>Your Order</h2>
							<ul class="list">
								<li>
									<a href="#">Product
										<span>Pirce</span>

									</a>
								</li>
                            </ul>
                                {% for object in cart.products.all %}
                            <ul class="list">
                                <li>
									<a href="#">{{object.title}}
										<span class="middle"></span>
										<span class="last">{{object.price}}</span>
									</a>
								</li>
                            </ul>
                            {% endfor %}
							<ul class="list list_2">
								<li>
									<a href="#">Subtotal
										<span>${{ cart.total}}</span>
									</a>
								</li>
								<li>
									<a href="#">Shipping
										<span>Flat rate: $5.99</span>
									</a>
								</li>
								<li>
									<a href="#">Total
										<span>{{order.total}}</span>
									</a>
								</li>
							</ul>
							<div class="payment_item">
								<div class="radion_btn">
									<input type="radio" id="f-option5" name="selector">
									<label for="f-option5">Check payments</label>
									<div class="check"></div>
								</div>
								<p>Please send a check to Store Name, Store Street, Store Town, Store State / County, Store Postcode.</p>
							</div>
							<div class="payment_item active">
								<div class="radion_btn">
									<input type="radio" id="f-option6" name="selector">
									<label for="f-option6">Paypal </label>
									<img src="img/product/single-product/card.jpg" alt="">
									<div class="check"></div>
								</div>
								<p>Please send a check to Store Name, Store Street, Store Town, Store State / County, Store Postcode.</p>
							</div>
							<div class="creat_account">
								<input type="checkbox" id="f-option4" name="selector">
								<label for="f-option4">I’ve read and accept the </label>
								<a href="#">terms & conditions*</a>
							</div>
							<a class="main_btn" href="#">Proceed to Paypal</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		{% endif %}
	</section>
	<!--================End Checkout Area =================-->







{% endblock %}

carts/templates/carts/snippetform.html
<form class="row contact_form" action="{%url 'accounts:login' %}" method="post" novalidate="novalidate">
    {% csrf_token %}
    {% if next %}
    <input type="hidden" name="next" value="{{next}}">
    {% endif %}
    <div class="col-md-6 form-group p_star">
        {{ form.as_table }}
    </div>
    <div class="col-md-12 form-group">
						<button type="submit" value="submit" class="btn submit_btn">Login To Continue</button>
						<div class="creat_account">
							<input type="checkbox" id="f-option" name="selector">
							<label for="f-option">Remember me</label>
						</div>
						<a class="lost_pass" href="#">Lost your password?</a>
					</div>
</form>

carts/templates/carts/updatecart.html
<form method="post" action="{% url 'carts:updatecart'%}" class="form">
    {% csrf_token %}
 <!--{{ cart }}-->
    <input type="hidden" name="product_id" value="{{ product.id }}">
    {% if in_cart %}
        <button type="submit" class="btn-danger">REMOVE</button>
    {% else %}
        {% if product in cart.products.all %}
            In Cart <button type="submit" class="main_btn btn-danger">REMOVE</button>
        {% else %}
             <button type="submit" class="main_btn btn-success">ADD TO CART</button>
        {% endif %}
    {% endif %}

</form>