carts/urls.py
from django.conf.urls import  url
from .views import cart
from products.views import update_cart,checkout_home

app_name = 'cart'

urlpatterns = [
 url(r'^$',cart,name='cart'),
 url(r'^updatecart/$',update_cart,name='updatecart'),
 url(r'^checkout/$',checkout_home,name='checkout'),


]

django_ecom/urls.py
from django.conf.urls import  url
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static
from products.views import ProductListView,\
    ProductDetailView,ProductFeaturedListView,ProductFeaturedDetailView
from carts.views import cart


urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^accounts/', include("accounts.urls", namespace='accounts')),
    url(r'^cart/', include("carts.urls", namespace='carts')),
    url(r'^$',ProductListView.as_view(), name='productlist'),
    path('featured', ProductFeaturedListView.as_view(), name='featured_list'),
    path('products/<slug:slug>', ProductDetailView.as_view(), name='productdetail'),
    url(r'^featured/(?P<slug>\d+)/$',ProductFeaturedDetailView.as_view())

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import re_path

from .views import ProductListView
# app_name = 'products'

# urlpatterns = [
#     re_path(r'^$',ProductListView.as_view(),name='productlist')
# ]

products/models.py
from django.db import models
import os
import random
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import  slugify
from django.db.models.signals import pre_save # right before the model save we gonna do something
from django.contrib.auth import get_user_model as user_model



def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name,ext = os.path.splitext(base_name)
    return name,ext

def upload_image_path(instance,filename):
    print(instance)
    print(filename)
    new_filename = random.randint(1,3910209312)
    name,ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext=ext)
    return 'products/{new_filename}/{final_filename}'.format(
        new_filename=new_filename,final_filename=final_filename
    )


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    User = user_model()

    # creator = models.ForeignKey(User,on_delete=models.CASCADE)
    creator = models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('post_by_category', args=[self.name])







class ProductQuerySet(models.QuerySet): # we can use Queryset API
    def featured(self):
        return self.filter(featured=True)# filter()- queryset-api- Returns a new QuerySet containing objects that match the given lookup parameters.

    def available(self):
        return self.filter(available=True)

    def get_by_id(self,slug):
        qs =  self.filter(slug=slug) #return  Product.object or single product
        if qs.count()==1: #Returns an integer representing the number of objects in the database matching the QuerySet.
            return qs.first() # Returns the first object matched by the queryset, or None if there is no matching object.
            # If the QuerySet has no ordering defined, then the queryset is automatically ordered by the primary key.
        return None

# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=30)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, null=True, blank=True)
    short_descriptiton = models.TextField()
    full_descriptiton = models.TextField()
    specification = models.TextField()
    quantity = models.PositiveIntegerField(blank=True,default=15)
    price = models.DecimalField(decimal_places=2,default=39.99,max_digits=20)
    image = models.ImageField(null=True,blank=True,upload_to=upload_image_path)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)


    # objects = ProductManager()
    objects = ProductQuerySet.as_manager()

    def __str__(self):
        return self.title # will return a string representation rather than product object

    def get_absolute_url(self): # to provide a link to a particular object or want to display that object's specific URL (if it has one) to the user
        return reverse("productdetail", kwargs={'slug': self.slug})
        #return '/products/{slug}'.format(slug=self.slug)

from .utils import unique_slug_generator

 # lets define a receiver signal function for creating slug which will takes a sender argument-in this case Produc Model, along with wildcard keyword arguments (**kwargs--slug); all signal handlers must take these arguments.
# The callback function which will be connected to the pre_save signal receiver
def pre_save_post_receiver(sender,instance, *args,**kwargs):  # here keyword instance arguments refer to the model itself to make sure this function send every time when we create title or slug we need a sender signal to do so
    if not instance.slug:  # if there is no slug present
        # instance.slug = create_slug(instance)
        instance.slug = unique_slug_generator(instance) # if slug field is not exist in the model ..generate it

# pre_save will sent at the beginning of a model’s save() method.
# here sender is the model class
# connect the  receiver to the signal
pre_save.connect(pre_save_post_receiver,sender=Product) # the sender will be the model class being saved, so you can indicate that you only want signals sent by some model:
# signal pre_save will run the function before every time a model is created or gets save

products/views.py
from django.shortcuts import render, Http404
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from .models import Product
from carts.models import Cart
from orders.models import Order
from billing.models import BillingProfile
from django.views.generic import ListView, DetailView, \
    CreateView, UpdateView, DeleteView, FormView  # Generic editing views for editing content


# Create your views here.

class ProductFeaturedListView(ListView):
    model = Product  # The model that this view will display data for
    template_name = 'home.html'
    # context_object_name = 'product'  # Designates the name of the variable to use in the context.
    paginate_by = 3
    # queryset = Product.objects.featured().active()

    # def get_queryset(self):
    #     return Product.objects.all()

    # def get_context_data(self, *args,  **kwargs):
    #     context = super(ProductFeaturedListView,self).get_context_data(*args,**kwargs)
    #     return context


class ProductFeaturedDetailView(DetailView):
    queryset = Product.objects.all()
    template_name = 'products/featured_product_detail.html'

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get(self.slug_url_kwarg)
        # instance = get_object_or_404(Post, slug=slug)
        instance = Product.objects.active().get_by_id(slug=slug)
        if instance is None:
            raise Http404('Product doesn\'t exist')
        return instance


class ProductListView(ListView):
    model = Product  # The model that this view will display data for
    template_name = 'home.html'
    # context_object_name = 'product'  # Designates the name of the variable to use in the context.
    # paginate_by = 3
    queryset = Product.objects.all()

    def get_context_data(self, *args, **kwargs):  # Returns context data for displaying the object.
        context = super(ProductListView, self).get_context_data(*args, **kwargs)
        return context


class ProductDetailView(DetailView):
    queryset = Product.objects.all()
    template_name = 'products/product_detail.html'

    def get_object(self, *args, **kwargs):  # Returns the single object that this view will display.
        request = self.request
        slug = self.kwargs.get('slug')  # look kwargs slug in the urls  instead of default pk
        # instance = get_object_or_404(Product, slug=slug)
        instance = Product.objects.get_by_id(slug)
        if instance is None:
            raise Http404('Product doesn\'t exist')
        return instance

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        cart_obj,new_obj = Cart.objects.get_cart_or_create(self.request)
        context['cart']=cart_obj
        return context

def update_cart(request):
    # product_id = 1 # take the first product as an item in the cart for implement the rest
    # print(request.POST)# because we passing a post request for the product through the form to add to cart by this function - change the database
    product_id = request.POST.get('product_id')  # we currently working with a existing product for dummy
    if product_id is not None:
        try:
        # Now lets fetch a product whose id is 1 and store it in obj
            product_obj = Product.objects.get(id=product_id)
        # Now lets fetch the carts current status - is there any item or not already
        except Product.DoesNotExist:
            print("Product is not available at this moment")
            return redirect("carts:cart")
        cart_obj, new_obj = Cart.objects.get_cart_or_create(request) # this will give us the current instance of the cart
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj) # This will work like toggle -Every time we update the cart either it will add item or remove item
        else:
            # Now add the product to this cart
            cart_obj.products.add(product_obj)  # cart_obj.products.add(product_id)
        request.session['cart_items'] = cart_obj.products.count()
        # return redirect(product_obj.get_absolute_url())
    return redirect('carts:cart') # namespace:url



def checkout_home(request):
    cart_obj, cart_created = Cart.objects.get_cart_or_create(request)  # this will give us the current instance of the cart
    order_obj = None
    if cart_created or cart_obj.products.count() == 0: # if the cart already exist in the view - store in the cache by a logged in user- we will redirect him to that cart
        return redirect('carts:cart')  # namespace:url
    else: # else-  we will make the order_obj when there is not any previous cart present or exist in the view- a new users continuous flow
        order_obj,new_order_obj = Order.objects.get_or_create(cart=cart_obj) # if there is not any existing cart in the order create and saved it

    user = request.user
    billing_profile = None
    login_form = AuthenticationForm
    if user.is_authenticated:
        billing_profile,billing_profile_created = BillingProfile.objects.get_or_create(user=user) #aslogged in user

    context = {
        'billing_profile':billing_profile,
        'order': order_obj,
        'cart': cart_obj,
        'login_form':login_form
    }






    return render(request,'carts/checkout.html',context)

products/templates/contact.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

  <!--================Home Banner Area =================-->
    <section class="banner_area">
        <div class="banner_inner d-flex align-items-center">
            <div class="container">
                <div class="banner_content text-center">
                    <h2>Contact Us</h2>
                    <div class="page_link">
                        <a href="index.html">Home</a>
                        <a href="contact.html">Contact Us</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Home Banner Area =================-->

    <!--================Contact Area =================-->
    <section class="contact_area p_120">
        <div class="container">
            <div id="mapBox" class="mapBox" data-lat="40.701083" data-lon="-74.1522848" data-zoom="13" data-info="PO Box CT16122 Collins Street West, Victoria 8007, Australia."
                data-mlat="40.701083" data-mlon="-74.1522848">
            </div>
            <div class="row">
                <div class="col-lg-3">
                    <div class="contact_info">
                        <div class="info_item">
                            <i class="lnr lnr-home"></i>
                            <h6>California, United States</h6>
                            <p>Santa monica bullevard</p>
                        </div>
                        <div class="info_item">
                            <i class="lnr lnr-phone-handset"></i>
                            <h6>
                                <a href="#">00 (440) 9865 562</a>
                            </h6>
                            <p>Mon to Fri 9am to 6 pm</p>
                        </div>
                        <div class="info_item">
                            <i class="lnr lnr-envelope"></i>
                            <h6>
                                <a href="#">support@colorlib.com</a>
                            </h6>
                            <p>Send us your query anytime!</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <form class="row contact_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name">
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email address">
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" id="subject" name="subject" placeholder="Enter Subject">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <textarea class="form-control" name="message" id="message" rows="1" placeholder="Enter Message"></textarea>
                            </div>
                        </div>
                        <div class="col-md-12 text-right">
                            <button type="submit" value="submit" class="btn submit_btn">Send Message</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!--================Contact Area =================-->

{% endblock %}

products/templates/home.html
{% extends 'base.html' %}
{% block content %}

<!--================Home Banner Area =================-->
    {% include 'partials/_home_banner.html' %}
<!--================Home Banner Area =================-->


<!--================Hot Deals Area =================-->
    {% include 'partials/_hot_deals.html' %}
<!--================Hot Deals Area =================-->


<!--================Clients Logo Area =================-->
    {% include 'partials/_clients_logo.html' %}
<!--================Clients Logo Area =================--



<!--================Feature Product Area =================-->
	<section class="feature_product_area section_gap">
		<div class="main_box">
			<div class="container-fluid">
				<div class="row">
					<div class="main_title">
						<h2>Featured Products</h2>
						<p>Who are in extremely love with eco friendly system.</p>
					</div>
				</div>
				<div class="row">
					{% for product in product_list %}
						<div class="col col1">
						<div class="f_p_item">
							<div class="f_p_img">
								<img class="img-fluid" src="{{ product.image.url }}" alt="">
								<div class="p_icon">
									<a href="#">
										<i class="lnr lnr-heart"></i>
									</a>
									<a href="{}">
										<i class="lnr lnr-cart"></i>
									</a>
								</div>
							</div>
							<a href="{{ product.get_absolute_url }}">
								<h4>{{ product.title }}</h4>
							</a>
							<h5> {{ product.price }}</h5>
						</div>
					</div>
					{% endfor %}
				</div>

				<div class="row">
					<nav class="cat_page mx-auto" aria-label="Page navigation example">
						<ul class="pagination">
							<li class="page-item">
								<a class="page-link" href="#">
									<i class="fa fa-chevron-left" aria-hidden="true"></i>
								</a>
							</li>
							<li class="page-item active">
								<a class="page-link" href="#">01</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">02</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">03</a>
							</li>
							<li class="page-item blank">
								<a class="page-link" href="#">...</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">09</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">
									<i class="fa fa-chevron-right" aria-hidden="true"></i>
								</a>
							</li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!--================End Feature Product Area =================-->


{% endblock %}